sudo: required
services:
  - docker

matrix:
  include:
    # Job for frontend app
    - language: node_js
      node_js:
        - stable
      before_script:
        - cd src/frontend
      cache:
        directories:
          - node_modules
      script:
        - yarn install
        - yarn run build
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t frontend .
        - docker images
        - docker tag frontend linkedpipes/applications:frontend
        - docker push linkedpipes/applications

    # Job for backend app
    - language: java
      jdk: oraclejdk10
      before_script:
        - cd src/backend
      script:
        - ./gradlew assemble
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t backend --build-arg JAR_FILE=build/libs/backend-0.0.1.jar .
        - docker images
        - docker tag backend linkedpipes/applications:backend
        - docker push linkedpipes/applications

branches:
  only:
    - master
