version: "3"
services:
  nginx: 
      image: nginx:stable
      container_name: lpa_reverse_proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 9001:80
      depends_on:
        - backend
        - frontend
  backend:
    image: linkedpipes/applications:backend
    container_name: lpa_backend
    build:
      context: src/backend/
    # ports:
    #   - "5000:8080"
    volumes:
      - "./src/backend/config.properties:/app/config.properties"

  frontend:
    image: linkedpipes/applications:frontend
    container_name: lpa_frontend
    build:
      context: src/frontend/
    # ports:
    #   - "9001:9001"


  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data
    # ports:
    #   - "8890:8890"

  discovery:
    image: linkedpipes/discovery
    container_name: lpa_discovery
    stdin_open: true
    # ports:
    #   - "8070:9000"
