version: "3"
services:
  backend:
    image: linkedpipes/applications:backend
    ports:
      - "8080:5000"

  frontend:
    # image: linkedpipes/applications:frontend
    build:
      context: src/frontend/
      args:
        REACT_APP_BASE_BACKEND_URL: http://localhost:5000/
    ports:
      - "9000:9000"
